### ISSUE TITLE
Concur brick not building

### ISSUE THREAD

**Issue by vimuel** [ajnsit/concur#11]
I'm getting the following build error:

```
   Configuring concur-brick-0.1.0.0...
    Preprocessing library concur-brick-0.1.0.0...
    [1 of 4] Compiling Concur.Brick.UI  ( src/Concur/Brick/UI.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Concur/Brick/UI.o )
    [2 of 4] Compiling Concur.Brick.Run ( src/Concur/Brick/Run.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Concur/Brick/Run.o )
    
    /Users/vilem/github/concur/concur-brick/src/Concur/Brick/Run.hs:40:35-39: error:
        Variable not in scope:
          runIO
            :: SuspendF [Image] (Free (Suspend [Image]) b) -> Maybe (IO ())
```

Is it still WIP?

**Comment by ajnsit** [comment]
Hey sorry, yes the brick backend is still WIP. Infact only the virtual-dom and react backends are usable. I'll add a note to the README.

**Comment by vimuel** [comment]
Ah great, thanks. I did try out the virtual-dom backend as well, but that didn't build.

**Comment by ajnsit** [comment]
Try building with `stack build --stack-yaml stack-ghcjs.yaml` so that it will build with GHCJS. The vdom library it uses is bitrotten and will take some work before it can be compiled with GHC for native executables.
