### ISSUE TITLE
`concur-vdom` won't build

### ISSUE THREAD

**Issue by mpdairy** [ajnsit/concur#2]
It has blank `ghcjs-ffiqq`  `ghcjs-vdom` dirs.

**Comment by robinvd** [comment]
did you clone it recursively?

```
git clone --recursive
```

ghcjs-ffiqq and ghcjs-vdom are git submodules

**Comment by ajnsit** [comment]
Yup, those folders are submodules. Try `git submodule update --init`.

**Comment by mpdairy** [comment]
Thanks, that was it!

**Comment by ajnsit** [comment]
Glad to hear it!
