### ISSUE TITLE
concur for idris?

### ISSUE THREAD

**Issue by mpdairy** [ajnsit/concur#20]
Hi @ajnsit have you ever considered trying to make Concur for the idris js backend? Here's the most promising/functional js lib I've tried for idris so far, which might be a good start: https://github.com/rbarreiro/idrisjs

**Comment by ajnsit** [comment]
I don't use idris, though it's on my list of things to learn. I would be happy to help out if someone wants to take a crack at it!

**Comment by ajnsit** [comment]
Closing this for now.
