### ISSUE TITLE
comparrison of react and vdom

### ISSUE THREAD

**Issue by robinvd** [ajnsit/concur#3]
Would be useful for choosing what backend to use

**Comment by ajnsit** [comment]
Currently vdom is a slightly more mature backend, but the API is slightly worse. I'm working on bringing the APIs in line. However if you like React, that's the way to go. It will also let you use any existing React components. I will publish an example of interop with React components soon.

**Comment by ajnsit** [comment]
I just published a complete example of wrapping a native React component.

[Drag Drop Sortable List Widget (React)](https://github.com/ajnsit/concur/blob/master/concur-react-components/sortable-tree/src/Main.hs) - [Demo](https://ajnsit.github.io/concur/examples/sortable-tree-example.jsexe/index.html) - Demonstrates Concur binding to [React-Sortable-Tree](https://github.com/fritz-c/react-sortable-tree).
