### ISSUE TITLE
Discussion forum

### ISSUE THREAD

**Issue by Saulzar** [ajnsit/concur#9]
Concur looks quite interesting. Do you have a place where people can discuss this with you/others?

**Comment by ajnsit** [comment]
I created gitter (https://gitter.im/concurhaskell) and reddit (https://www.reddit.com/r/concurhaskell/) communities. Please feel free to ask any questions!

**Comment by Saulzar** [comment]
Thanks - I've asked a few questions on the gitter channel, would be interested to hear your thoughts if you have time :)
